server:
  port: 8080
spring:
  application:
    name: fire-digital-platform
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/fire_digital_platform?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: gaoqianxiaodui123
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 15
      max-active: 30
      min-idle: 5
      max-wait: 60000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

logging:
  pattern:
    console: "%d %thread %5level %logger{50} : %line %msg%n"
  config: classpath:log4j2.xml
#  config: classpath:logback.xml


swagger:
  enable: true
  title: ${spring.application.name}
  description: 接口api
  version: 1.0
  name: 接口api
  apiBasePackage: com.huajie.application.api