server:
  port: 8080
spring:
  application:
    name: fire-digital-platform
  datasource:
    url: jdbc:mysql://see_readme:3306/fire_digital_platform
    username: see_readme
    password: see_readme
    driver-class-name: com.mysql.jdbc.Driver

swagger:
  enable: true
  title: ${spring.application.name}
  description: 接口api
  version: 1.0
  name: 接口api
  apiBasePackage: com.huajie.FireDigitalPlatformBootStarter