package com.huajie.infrastructure.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.huajie.domain.entity.NotifyForNotice;
import com.huajie.domain.entity.NotifyForNoticeExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface NotifyForNoticeMapper extends BaseMapper<NotifyForNotice> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    long countByExample(NotifyForNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int deleteByExample(NotifyForNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int insertSelective(NotifyForNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    List<NotifyForNotice> selectByExample(NotifyForNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    NotifyForNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") NotifyForNotice record, @Param("example") NotifyForNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") NotifyForNotice record, @Param("example") NotifyForNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NotifyForNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NotifyForNotice record);

    void insertBatch(List<NotifyForNotice> notifyForNoticeList);
}