package com.huajie.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table notify_for_notice
 */
public class NotifyForNotice implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_for_notice.id
     *
     * @mbg.generated
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_for_notice.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   通知id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_for_notice.notice_id
     *
     * @mbg.generated
     */
    private Integer noticeId;

    /**
     * Database Column Remarks:
     *   发送人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_for_notice.send_user_id
     *
     * @mbg.generated
     */
    private Integer sendUserId;

    /**
     * Database Column Remarks:
     *   发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notify_for_notice.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_for_notice.id
     *
     * @return the value of notify_for_notice.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_for_notice.id
     *
     * @param id the value for notify_for_notice.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_for_notice.user_id
     *
     * @return the value of notify_for_notice.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_for_notice.user_id
     *
     * @param userId the value for notify_for_notice.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_for_notice.notice_id
     *
     * @return the value of notify_for_notice.notice_id
     *
     * @mbg.generated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_for_notice.notice_id
     *
     * @param noticeId the value for notify_for_notice.notice_id
     *
     * @mbg.generated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_for_notice.send_user_id
     *
     * @return the value of notify_for_notice.send_user_id
     *
     * @mbg.generated
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_for_notice.send_user_id
     *
     * @param sendUserId the value for notify_for_notice.send_user_id
     *
     * @mbg.generated
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notify_for_notice.send_time
     *
     * @return the value of notify_for_notice.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notify_for_notice.send_time
     *
     * @param sendTime the value for notify_for_notice.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify_for_notice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", noticeId=").append(noticeId);
        sb.append(", sendUserId=").append(sendUserId);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}